### ISSUE TITLE
Bash completion needs updated to support running without .scuba.yml

### ISSUE THREAD

**Issue by combsjy** [JonathonReinhart/scuba#101]
With v2.1.0 it is possible to run `scuba` without a `.scuba.yml` file.  If you attempt to do this, tab completion will fail with an error:
```
.scuba.yml not found here or any parent up to mount point
```

**Comment by JonathonReinhart** [comment]
How should scuba react in this situation? Should it only try to complete the `--image` argument?

**Comment by TimothySprague** [comment]
This should be addressed by the use of `argcomplete` per #136.

**Comment by JonathonReinhart** [comment]
Resolved by #162.
