### ISSUE TITLE
Drop support for Python 2.6

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#118]
[Python 2.6.9](https://www.python.org/download/releases/2.6.9/) was released 2013-10-29, nearly five years ago, and officially retired Python 2.6.

It's time to drop support for Python 2.6. Other projects are doing the same:
- pypa/pip#3955

There's a fair amount of Python 2.6 baggage in Scuba:
- Use of `'{0}'` in string formatting, as opposed to auto-numbering `'{}'`
- [`compat.check_output`](https://github.com/JonathonReinhart/scuba/blob/daf9a9680c81985b9671381db7ad57fb5faf91f2/scuba/compat.py#L34), because Python 2.6 doesn't have `subprocess.check_output()`
- [`utils.shlex_split`](https://github.com/JonathonReinhart/scuba/blob/daf9a9680c81985b9671381db7ad57fb5faf91f2/scuba/utils.py#L13), because Python 2.6 has a problem with Unicode arguments

This is a good candidate for the 3.0 milestone.

**Comment by hugovk** [comment]
👍 

Python 3.2 and 3.3 are also EOL (since 2016-02-27 and 2017-09-29 respectively) and no longer receiving security updates (or any updates) from the core Python team.

At least dropping 3.2 is a good thing as it can simplify Unicode handling, and 3.3 generally isn't used much: people using Python 3 have been upgrading more regularly.

You can then run https://github.com/asottile/pyupgrade to automatically upgrade syntax for newer versions of the language.

**Comment by JonathonReinhart** [comment]
Thanks for the comment, @hugovk!

Yes, I think I will also drop support for Python 3.2 also. This occurred to me when I saw that my [`staticx` project](https://github.com/JonathonReinhart/staticx)'s builds were failing on Python 3.2. (See https://github.com/JonathonReinhart/staticx/issues/64).

> At least dropping 3.2 is a good thing as it can simplify Unicode handling,

Can you elaborate on this? I'm familiar with the difference in Unicode handling between Python 2 and 3, but not so much about 3.2 and 3.3.

**Comment by hugovk** [comment]
> The biggest change made specifically to ease migration from Python 2 was the reintroduction of Unicode literals in Python 3.3 (in PEP 414). This allows developers supporting both Python 2 and 3 in a single code base to easily distinguish binary literals, text literals and native strings, as `b"binary"` means bytes in Python 3 and str in Python 2, `u"text"` means str in Python 3.3+ and unicode in Python 2, while `"native"` means str in both Python 2 and 3.

https://python-notes.curiousefficiency.org/en/latest/python3/questions_and_answers.html#what-changes-in-python-3-have-been-made-specifically-to-simplify-migration

> This PEP proposes that Python 3.3 restore support for Python 2's Unicode literal syntax, substantially increasing the number of lines of existing Python 2 code in Unicode aware applications that will run without modification on Python 3.

https://www.python.org/dev/peps/pep-0414/
