### ISSUE TITLE
Add supplementary groups in the container

### ISSUE THREAD

**Issue by mpdude** [JonathonReinhart/scuba#142]
For example when bind-mounting the Docker socket into a running container as described in #141, it may be necessary for the user *inside* the container to belong to additional groups (for example, to be allowed to access that socket).

`docker run` has the `--group-add` option which would be used and be populated with the additional groups the user has on the host machine.

**Comment by xanarin** [comment]
@JonathonReinhart I believe this feature is now possible with the addition of the `docker_args:` directive in #177. One would just specify:
```yaml
docker_args: '--group-add audio'
```

I think this issue can be closed.

**Comment by JonathonReinhart** [comment]
I agree that `docker_args` is a good way to handle this fairly corner-case request.

@mpdude I'm going to close this issue but please feel free to comment or reopen if that is insufficient.
