### ISSUE TITLE
Scuba cannot function on Docker Images missing /bin/sh

### ISSUE THREAD

**Issue by xanarin** [JonathonReinhart/scuba#143]
[Kaniko](https://github.com/GoogleContainerTools/kaniko) is "a tool to build container images from a Dockerfile, inside a container or Kubernetes cluster." This makes it possible to build Docker images in Scuba and in Gitlab CI using a Docker runner.

However, the Docker image for Kaniko is **extremely** stripped down. The base image doesn't even have a shell in it, but the [debug image](https://github.com/GoogleContainerTools/kaniko#debug-image) does. However, the shell is in the `debug` image is located at `/busybox/sh`, and there is no `/bin/sh`. This causes Scuba to be non-functional because it requires `/bin/sh` to exec the `.scuba/command.sh` script:
```
$ scuba --version
scuba 2.3.0+49.g5bd095a

$ scuba --image gcr.io/kaniko-project/executor:debug echo "hi"
Error: unknown command "/bin/sh" for "executor"
Run 'executor --help' for usage.

$ sudo scuba --image gcr.io/kaniko-project/executor:debug --entrypoint="/busybox/sh" echo "hi"
/busybox/sh: can't open '/bin/sh': No such file or directory
```

To be able to use the Kaniko image with Scuba (and be able to build Docker images in Scuba), I think Scuba will need to have a flag (and maybe a `.scuba.yml` config option) to change which shell Scuba targets with the `command.sh` script.

**Comment by JonathonReinhart** [comment]
We can add a `--shell`  command line option and everywhere there is an `image:` in `.scuba.yml` add an accompanying `shell:`

This simply gets put here:
https://github.com/JonathonReinhart/scuba/blob/5bd095a3f67cf77d29f9155c5fe23cfc3900f2af/scuba/__main__.py#L318
