### ISSUE TITLE
The docker args flag gives requires one arg error

### ISSUE THREAD

**Issue by wynn-rj** [JonathonReinhart/scuba#175]
Currently Scuba's -d or --docker-args flag that allows the user to specify arguments that should be passed-through to docker will give an error when passing a volume to docker.

```
$ scuba -d "-v $(pwd)/../external:$(pwd)/../external" ./test.sh                                 
usage: scuba [-h] [-d DOCKER_ARGS] [-e ENV_VARS] [--entrypoint ENTRYPOINT]
             [--image IMAGE] [--shell SHELL] [-n] [-r] [-v] [-V]
             ...
scuba: error: argument -d/--docker-arg: expected one argument
```
When the arguments are passed with either an equals sign or no space it works as intended
```
$ scuba -d"-v $(pwd)/../external:$(pwd)/../external" ./test.sh                                  
Hi there
$ scuba -d="-v $(pwd)/../external:$(pwd)/../external" ./test.sh                                 
Hi there
```
If this is intended behavior, it would be useful for an end user to know of this condition.

My setup used for reproducing this is as follows
```
$ ls -A *                                                                                                 
external:
total 4
-rw-r--r-- 1 wynn-rj wynn-rj    9 Nov 23 16:51 message

scuba-proj:
total 8
-rw-r--r-- 1 wynn-rj wynn-rj   15 Nov 23 16:56 .scuba.yml
-rwxr-xr-x 1 wynn-rj wynn-rj   34 Nov 23 16:51 test.sh

$ cat scuba-proj/.scuba.yml                                                                                
image: busybox

$ cat scuba-proj/test.sh                                                                                   
#!/bin/sh
cat ../external/message

$ cat external/message
Hi there

$ scuba -v                                                                                                 
scuba 2.7.0
```

**Comment by JonathonReinhart** [comment]
> When the arguments are passed with either an equals sign or no space it works as intended

Yes, this is just a limitation of Python's [`argparse`](https://docs.python.org/3/library/argparse.html); it first scans the command line looking for hyphen-prefixed arguments, assumes that they are options, and then tries to match up the option values to them. So in your case, argprase assumes the `-v` is the `scuba -v` argument, and that your `-d` option had no option value.

Your workaround with an equal sign is exactly what I suggest: `-d='-v /foo:/bar'`.

I will address this during #181.
