### ISSUE TITLE
Request verbosity related command line options

### ISSUE THREAD

**Issue by combsjy** [JonathonReinhart/scuba#19]
It would be nice to have a verbose (-v) command line option to print information about its interactions with the underlying docker system.

It would also be useful to have a dry run (-n) command to print out the underlying docker command scuba would run without actually running it.

- [x] Verbose option (-v)
- [ ] Dry run option (-n)

**Comment by JonathonReinhart** [comment]
`-v` (lowercase) is already used by `--version`, so the short form of `--verbose` is `-V` (uppercase).
