### ISSUE TITLE
Host scuba on PyPi

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#20]
Hosting this package on [PyPi](https://pypi.python.org/pypi) will make it easier to install and use.

References:
- [How to submit a package to PyPI](http://peterdowns.com/posts/first-time-with-pypi.html)
- [PyPI deployment - Travis CI](https://docs.travis-ci.com/user/deployment/pypi)

**Comment by ava-dylang** [comment]
:+1: :+1:

**Comment by JonathonReinhart** [comment]
Done!

Scuba is now hosted on PyPI: https://pypi.python.org/pypi/scuba

Related commits:
- 2817a2bbe28ab15901fbbc3c336c2d7cd77a46fb
- 3c9ca2418738ef54dcebc293061ebe00b365ed60

**Comment by ava-dylang** [comment]
Excellent, but I don't notice a link to the pypi page from the readme, I see in the diff that the pypi badge does link there. Perhaps its a personal problem that I never consider badges as something I should look for links in. Anyway, cool!

**Comment by JonathonReinhart** [comment]
Good call. I updated the README. (e9005680516ba963efea767116af231cb0c543db)
