### ISSUE TITLE
Unable to write to host bind mounted directory from container on OSX using boot2docker

### ISSUE THREAD

**Issue by jstoneburner** [JonathonReinhart/scuba#4]
-u flag doesn't work under mac boot2docker

**Comment by JonathonReinhart** [comment]
Try running scuba with this fix and see if it works for you.

    $ cd scuba
    $ git fetch
    $ git checkout fix-remote-docker
    
    $ cd wherever
    $ /path/to/scuba/repo/src/scuba whatever args

**Comment by JonathonReinhart** [comment]
For reference, I'm not sure exactly how host bind mounts on OSX+boot2docker work.  I assume there is some sort of filesharing component to the docker remote protocol.

Here are some related Docker issues; none of them is clear exactly how this works, or why we might be seeing this issue:
- docker/docker#4023
- docker/docker#7249

**Comment by jstoneburner** [comment]
Fix works - I am now getting the same build messages on the host system that I am getting in interactive mode on the docker image.

**Comment by JonathonReinhart** [comment]
This fix is included in [v1.1.2](https://github.com/JonathonReinhart/scuba/releases/tag/v1.1.2).
