### ISSUE TITLE
Implement bash completion

### ISSUE THREAD

**Issue by combsjy** [JonathonReinhart/scuba#46]
A feature that allows scuba to list aliases will allow one to enable bash command completion.

**Comment by JonathonReinhart** [comment]
We'll add multiple command-line arguments which will dump things out for the completion script:
- aliases
- options

**Comment by JonathonReinhart** [comment]
Can we install the bash completion as part of `setup.py`?

http://stackoverflow.com/questions/9944320/install-bash-completion-together-with-distutils-pip
