### ISSUE TITLE
Allow searching up the directory hierarchy for .scuba.yml

### ISSUE THREAD

**Issue by JonathonReinhart** [JonathonReinhart/scuba#6]
Currently, since one `.scuba.yml` is intended to be checked-in at the top-level project directory, commands can only be invoked from that top-level directory, and not any sub-directories.

- Make scuba search up through the directory hierarchy for a `.scuba.yml` file
- That directory becomes the root of the -v mount
- The working directory is set to the subdirectory in which scuba was invoked (relative to the -v mount)

One outstanding question is whether or not to enable searching by default.
- SCons enables this feature only with a `-u` or `-U` option.
- Git does this by default.

When implementing this, the following considerations must be made:
- Like Git, stop at a filesystem boundary

Thanks @combsjy for helping with the idea.

**Comment by JonathonReinhart** [comment]
@jstoneburner Try out the `add-search` branch.

**Comment by combsjy** [comment]
+1

**Comment by JonathonReinhart** [comment]
Closed via PR #8.
