### ISSUE TITLE
Scuba -n wrapped line printing raises problems with copy/paste

### ISSUE THREAD

**Issue by combsjy** [JonathonReinhart/scuba#63]
A workflow that I use regularly is to run ```scuba -n``` to generate the docker command line for me to run so that I can easily copy/paste/edit that command line.  With the output on multiple lines, after I paste I can only edit the last line.  

I would prefer the output not span multiple lines and not split the output across multiple lines.

Admittedly this is an EXTREMELY minor issue and if never done or if regected can easily be worked around.

**Comment by JonathonReinhart** [comment]
The `-n` option was really intended as a debugging option. Admittedly, it was quite useful for users during the early days, before scuba acquired many features. Now, we have `-d` to specify additional arguments to `docker run`, as well as support for richer aliases in the `.scuba.yml` file.

Considering this was already revamped once, and I strive for highly-tested code, I'd rather not change this again, or add an additional option. I would rather spend development cycles on additional features. If there's something you frequently find yourself needing to manually add to or change in the docker command line, please open an issue for that.

Finally, as a workaround, you might consider using vi-mode in your shell. Then, once you've copy & pasted the (multi-line) docker command line to your shell prompt, hit <kbd>ESC</kbd>, <kbd>v</kbd> to edit the command line in "visual" mode. Then you should be able to edit to your heart's content in a real editor.
